import fs from "fs";
import mock from "mock-fs";
import { Rewriter } from 'synvert-core';
import { getFileName } from "./utils";

class Verifier {
  constructor(private snippet: string, private extension: string, private inputs: string[], private outputs: string[]) { }

  call(): boolean {
    try {
      return this.inputs.every((input, index) => {
        const fileName = getFileName(this.extension);
        const snippet = `
          const Synvert = require("synvert-core");
          new Synvert.Rewriter("group", "name", () => {
            configure({ parser: 'typescript' });
            withinFile("${fileName}", () => {
              ${this.snippet}
            });
          });
        `;
        // FIXME: runInVM is not working here,
        // considering snippet is generated by us,
        // it's safe to call `eval`.
        eval(snippet);
        const rewriter = Rewriter.rewriters["group"]["name"];
        mock({ [fileName]: input });
        rewriter.process();
        return fs.readFileSync(fileName, "utf-8") == this.outputs[index];
      });
    } finally {
      Rewriter.rewriters = {};
      mock.restore();
    }
  }
}

export default Verifier;